name: py310

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
    - -i http://mirrors.aliyun.com/pypi/simple/
    - langfuse
  - jupyterlab
  - langchain
  - fastapi[standard]
