name: py310

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
    - -i http://mirrors.aliyun.com/pypi/simple/
    - --trusted-host mirrors.aliyun.com
    - langfuse=2.59.3
    - langchain=0.3.19
  - jupyterlab
  - fastapi[standard]
