name: py312

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - jupyterlab
  - pip
  - pip:
    - -i http://mirrors.aliyun.com/pypi/simple/
    - --trusted-host mirrors.aliyun.com
    - langchain==0.3.19
    - Langfuse==2.59.3
    - langserve==0.3.1
    - langchain-openai==0.3.6
    - langgraph==0.2.74
    - sse-starlette==2.2.1
    - fastapi[standard]==0.115.8
